services:
  - type: web
    name: jobnimbus-mcp-server
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Force rebuild timestamp: 2025-10-11T04:30:00Z
